Productionize - Code works seamlessly with a Rails App
DEFRA/ea-validation pull request #7
Opened 2016-09-19 13:20 UTC by autotelik

Add engine code so validators and default locale messages exported to App

2016-09-21 09:00 UTC, autotelik commented
:eyes:

2016-09-21 12:01 UTC, lewispb commented on lib/ea/validation/grid_reference_validator.rb
> +        record.errors.add attribute, @message || I18n.t("ea.validation.errors.grid_reference.invalid")
best practice would be to use the `message` method here

2016-09-21 12:07 UTC, lewispb requested changes
Can you also run `rubocop -a` over this project? Thanks

2016-09-21 12:07 UTC, lewispb commented on config/locales/error.en.yml
> +              </br>If your number has only 7 digits, enter it with a zero at the start.
Maybe this would be better for line breaks:

http://stackoverflow.com/questions/10982706/how-to-break-lines-in-yml-localization-files-on-rails

```
          invalid: |
              Enter a valid number - it should have 8 digits, or 2 letters followed by 6 digits
              If your number has only 7 digits, enter it with a zero at the start.
```

2016-09-21 12:07 UTC, lewispb commented on lib/ea/engine.rb
> +      app.config.i18n.load_path += Dir[config.root.join("config/locales/**/**/", "*.{rb,yml}").to_s]
join takes an array so we can lose the slashes, helps with cross platform compatibility

2016-09-21 12:07 UTC, lewispb commented on lib/ea/engine.rb
> +    config.autoload_paths += Dir["#{config.root}/lib/**/"]
Could use File.join here instead? 

https://richonrails.com/articles/basic-file-and-directory-operations-in-ruby

2016-09-21 14:59 UTC, autotelik commented on config/locales/error.en.yml
> +              </br>If your number has only 7 digits, enter it with a zero at the start.
not sure .. cos this is to produce a line break in the displayed HTML

2016-09-21 15:04 UTC, lewispb commented on config/locales/error.en.yml
> +              </br>If your number has only 7 digits, enter it with a zero at the start.
Perhaps not every service that uses this gem would want the `<br>`, and if they do they could use simple_format

http://apidock.com/rails/ActionView/Helpers/TextHelper/simple_format

2016-09-21 15:13 UTC, autotelik commented on config/locales/error.en.yml
> +              </br>If your number has only 7 digits, enter it with a zero at the start.
i though by using locales another service can easily over ride the message in their app in their own locale files

2016-09-21 15:28 UTC, autotelik commented on lib/ea/validation/grid_reference_validator.rb
> +        record.errors.add attribute, @message || I18n.t("ea.validation.errors.grid_reference.invalid")
fixed but not showing up here for some reason

2016-09-21 15:28 UTC, autotelik commented on lib/ea/engine.rb
> +      app.config.i18n.load_path += Dir[config.root.join("config/locales/**/**/", "*.{rb,yml}").to_s]
fixed but not showing up here for some reason

2016-09-21 16:03 UTC, autotelik commented
@lewispb rubocop done .. not sure how to respond 'officially' to the requested changes thang

2016-09-22 08:16 UTC, lewispb commented on config/locales/error.en.yml
> +              </br>If your number has only 7 digits, enter it with a zero at the start.
Ok, good point :+1:

2016-09-22 08:16 UTC, lewispb approved these changes

2016-09-22 08:29 UTC, merged